const SET_ADMIN_REGIONS_DATA = 'SET_ADMIN_REGIONS_DATA';
const SET_ADMIN_CITIES_DATA = 'SET_ADMIN_CITIES_DATA';
const SET_ADMIN_ATTRACTIONS_DATA = 'SET_ADMIN_ATTRACTIONS_DATA';
const SET_ADMIN_CULTURES_DATA = 'SET_ADMIN_CULTURES_DATA';
const SET_ADMIN_DISHES_DATA = 'SET_ADMIN_DISHES_DATA';

export default {
  SET_ADMIN_REGIONS_DATA,
  SET_ADMIN_CITIES_DATA,
  SET_ADMIN_ATTRACTIONS_DATA,
  SET_ADMIN_CULTURES_DATA,
  SET_ADMIN_DISHES_DATA,
};
