const SET_ADMIN_REGIONS_DATA = 'SET_ADMIN_REGIONS_DATA';
const SET_ADMIN_CITIES_DATA = 'SET_ADMIN_CITIES_DATA';
const SET_ADMIN_ATTRACTIONS_DATA = 'SET_ADMIN_ATTRACTIONS_DATA';
const SET_ADMIN_CULTURES_DATA = 'SET_ADMIN_CULTURES_DATA';
const SET_ADMIN_DISHES_DATA = 'SET_ADMIN_DISHES_DATA';
const SET_ADMIN_CATEGOIES_DATA = 'SET_ADMIN_CATEGOIES_DATA';
const REMOVE_ADMIN_REGION_DATA = 'REMOVE_ADMIN_REGION_DATA';
const REMOVE_ADMIN_CITY_DATA = 'REMOVE_ADMIN_CITY_DATA';
const REMOVE_ADMIN_ATTRACTIONS_DATA = 'REMOVE_ADMIN_ATTRACTION_DATA';
const REMOVE_ADMIN_CULUTRE_DATA = 'REMOVE_ADMIN_CULUTRE_DATA';
const REMOVE_ADMIN_DISH_DATA = 'REMOVE_ADMIN_DISH_DATA';
const REMOVE_ADMIN_CATEGORY_DATA = 'REMOVE_ADMIN_CATEGORY_DATA';

export default {
  SET_ADMIN_REGIONS_DATA,
  SET_ADMIN_CITIES_DATA,
  SET_ADMIN_ATTRACTIONS_DATA,
  SET_ADMIN_CULTURES_DATA,
  SET_ADMIN_DISHES_DATA,
  SET_ADMIN_CATEGOIES_DATA,
  REMOVE_ADMIN_REGION_DATA,
  REMOVE_ADMIN_CITY_DATA,
  REMOVE_ADMIN_ATTRACTIONS_DATA,
  REMOVE_ADMIN_CULUTRE_DATA,
  REMOVE_ADMIN_DISH_DATA,
  REMOVE_ADMIN_CATEGORY_DATA,
};
